# Meteor 共享配置（master + worker + client 共用）
meteor {
  client {
    push {
      replicate = true
      max-reqs-in-flight = 32
      buffer-size = 64k
      queue-capacity = 512
    }
    fetch {
      max-reqs-in-flight = 32
    }
  }

  shuffle {
    partition {
      split-threshold = 1g
    }
  }
}
